### PR TITLE
Ispc code for upstreaming

### PR DESCRIPTION
**Pull request by borg323**
The ispc TranformOut is still giving a small nps improvement over the cache aware version (at least on some architectures). I have also added an implementation of TransformOut giving about 5% more nps. 
I also did some clean-ups and made the build system make code for several architectures, selected at run time.

Since this is largely your work, I would prefer the pr to be credited to you. So, I am making the pull request against your tree. You can do any changes you think appropriate before making an upstream pull request.

### CODE REVIEW

**Comment by ra1u** [comment]
Thank you for this. 

It seems there is problem on my machine to link multiple object files generated by ispc.

    [132/163] Linking target lc0.
    FAILED: lc0 
    ccache c++  -o lc0 'lc0@exe/winograd.o' 'lc0@exe/winograd_sse2.o' 'lc0@exe/winograd_sse4.o' 'lc0@exe/winograd_avx.o' 'lc0@exe/winograd_avx11.o' 'lc0@exe/meson-generated_proto_net.pb.cc.o' 'lc0@exe/src_main.cc.o' 'lc0@exe/src_engine.cc.o' 'lc0@exe/src_version.cc.o' 'lc0@exe/src_chess_bitboard.cc.o' 'lc0@exe/src_chess_board.cc.o' 'lc0@exe/src_chess_position.cc.o' 'lc0@exe/src_chess_uciloop.cc.o' 'lc0@exe/src_mcts_node.cc.o' 'lc0@exe/src_mcts_search.cc.o' 'lc0@exe/src_neural_cache.cc.o' 'lc0@exe/src_neural_encoder.cc.o' 'lc0@exe/src_neural_factory.cc.o' 'lc0@exe/src_neural_loader.cc.o' 'lc0@exe/src_neural_network_check.cc.o' 'lc0@exe/src_neural_network_mux.cc.o' 'lc0@exe/src_neural_network_random.cc.o' 'lc0@exe/src_neural_network_st_batch.cc.o' 'lc0@exe/src_neural_writer.cc.o' 'lc0@exe/src_selfplay_game.cc.o' 'lc0@exe/src_selfplay_loop.cc.o' 'lc0@exe/src_selfplay_tournament.cc.o' 'lc0@exe/src_utils_commandline.cc.o' 'lc0@exe/src_utils_optionsdict.cc.o' 'lc0@exe/src_utils_optionsparser.cc.o' 'lc0@exe/src_utils_random.cc.o' 'lc0@exe/src_utils_string.cc.o' 'lc0@exe/src_utils_transpose.cc.o' 'lc0@exe/src_utils_filesystem.posix.cc.o' 'lc0@exe/src_neural_blas_batchnorm.cc.o' 'lc0@exe/src_neural_blas_convolution1.cc.o' 'lc0@exe/src_neural_blas_fully_connected_layer.cc.o' 'lc0@exe/src_neural_blas_winograd_convolution3.cc.o' 'lc0@exe/src_neural_blas_network_blas.cc.o' 'lc0@exe/src_neural_opencl_OpenCL.cc.o' 'lc0@exe/src_neural_opencl_OpenCLTuner.cc.o' 'lc0@exe/src_neural_opencl_network_opencl.cc.o' -Wl,--no-undefined -Wl,--as-needed -Wl,-O1 -Wl,--start-group /usr/lib/x86_64-linux-gnu/libprotobuf.so -lpthread /usr/lib/x86_64-linux-gnu/libopenblas.so /usr/lib/x86_64-linux-gnu/libOpenCL.so /usr/lib/x86_64-linux-gnu/libz.so -Wl,--end-group  
    /usr/bin/ld: lc0@exe/winograd.o: relocation R_X86_64_PC32 against symbol `abort@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
    /usr/bin/ld: final link failed: bad value
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.


However, linking single file as was originally done, works. I am now rebuilding ispc with extra patches, and will report.

Extra.

I merged this in ra1u/ispc2 branch

**Comment by borg323** [comment]
I usually call meson with `-Ddefault_library=static` which I thought may have masked the problem. However even with  `-Ddefault_library=shared` (or without it) the build went fine and the executable works. I have also tested it using windows with vs2017 without issues. Try building a static library to see if this helps, maybe we'll figure it out.

I need the multiple targets for compiling binaries for distribution, that need to work an both old and new systems. The tests @frpays run had some combinations that were slower, when using a binary made for an sse4 target.

**Comment by ra1u** [comment]
I was not able to build this way. I have fixed build system to overcome this issue (for me) and patch is available here in master now. 

Looking for feedback and  to push this on upstream.

**Comment by borg323** [comment]
I saw the changes - I think it is better to change the "ispc" option to build the local version (on by default) and add a new one, "ispc_release", to make the multi-targeted version.

**Comment by ra1u** [comment]
there is currently added ispc_native_only variable. I think that changing defult, on true should have same effect. 

https://github.com/ra1u/lc0/blob/5fc5e6ea2d1658dce3ab5af78fea0eae668d1451/meson_options.txt#L78

**Pull request merged**
